FROM ry-c4tkg-uat-tkc01-harbor.ssomgmt.go.th/wcf2/node:20-alpine

#
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json ./

# Set proxy configuration for npm
RUN npm config set proxy http://172.16.11.231:8080
RUN npm config set https-proxy http://172.16.11.231:8080

# Install dependencies
RUN npm install --ignore-scripts --legacy-peer-deps --loglevel verbose

# Copy the rest of the application code
COPY . .

# Link the component library
RUN npm link

CMD ["tail", "-f", "/dev/null"]