version: "3.8"

services:
  storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "6006:6006"
    command: npm run storybook
